public class P5_OrderProcessingWithjoin {
    public static void main(String[] args) {

        // creating 3 thread object
        PaymentTask payment = new PaymentTask();
        InvoiceTask invoice = new InvoiceTask();
        EmailTask2 email = new EmailTask2();

        try {
            // 1: Payment first
            payment.start();
            payment.join();   // invoice thread waits until payment finishes

            // 2: Invoice after payment
            invoice.start();
            invoice.join();   // email thread waits until invoice finishes

            // 3: Email after invoice
            email.start();
            email.join();     // main waits until email finishes

        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("All child Thread done I am main thread");
    }
}

class PaymentTask extends Thread {
    public void run() {
        System.out.println("Payment completed by " + Thread.currentThread().getName());
    }
}

class InvoiceTask extends Thread {
    public void run() {
        System.out.println("Invoice generated by " + Thread.currentThread().getName());
    }
}

class EmailTask2 extends Thread {
    public void run() {
        System.out.println("Email sent by " + Thread.currentThread().getName());
    }
}



/*
2. Payment done, Invoice generated, email sent, I am main thread
3. Order cannot be changed as join is used after every thread executed which make sure one thread finishes first before starting second
4. Payment thread printing payment done, Invoice thread printing invoice generated, email thread printing email sent, main thread printing I am main
7. In real life we can use this method to control flow of certain thread but in limit other wise it wont be any use of multithreading
*/