public class P5_OrderProcessingWithjoin {
    public static void main(String[] args) {

        // creating 3 thread object
        PaymentTask payment = new PaymentTask();
        payment.setName("Payment-Thread");

        InvoiceTask invoice = new InvoiceTask();
        invoice.setName("Invoice-Thread");

        EmailTask2 email = new EmailTask2();
        email.setName("Email-Thread");

        try {
            // 1: Payment first
            payment.start();
            payment.join();   // invoice thread waits until payment finishes

            // 2: Invoice after payment
            invoice.start();
            invoice.join();   // email thread waits until invoice finishes

            // 3: Email after invoice
            email.start();
            email.join();     // main waits until email finishes

        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        System.out.println("All child Thread done I am " + Thread.currentThread().getName() + " thread");
    }
}

class PaymentTask extends Thread {
    public void run() {
        System.out.println("Payment completed by " + Thread.currentThread().getName());
    }
}

class InvoiceTask extends Thread {
    public void run() {
        System.out.println("Invoice generated by " + Thread.currentThread().getName());
    }
}

class EmailTask2 extends Thread {
    public void run() {
        System.out.println("Email sent by " + Thread.currentThread().getName());
    }
}

/*
## Program 5: Order Processing With join()

Create three threads:
	PaymentTask
	InvoiceTask
	EmailTask

Rules:
	1. Payment should complete first.
	2. Invoice should generate after payment.
	3. Email should send after invoice.

Use join() to control order
 */

/*
2. Payment done, Invoice generated, email sent, I am main thread
3. Order cannot be changed as join is used after every thread executed which make sure one thread finishes first before starting second
4. Payment thread prints "payment completed", Invoice thread prints "invoice generated", email thread prints "email sent", main thread prints "I am main"
7. In real life we can use this method to control flow of certain thread but in limit other wise it wont be any use of multithreading
*/

